services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "LetMeIn123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "9930:9910"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9910
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyAppDb;User Id=sa;Password=LetMeIn123;Encrypt=False;
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "9900:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=http://backend:9910
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network:
